### PR TITLE
DownloadTests

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by nesk** [comment]
Hi Peter!

I will list my observations here, it will be way more handy than using Telegram.

# About your questions

>Images aren't ideal as they aren't actually downloaded - they are presented in a preview-page. My plan to test it with images ended here.

>PDFs show a similar blank page behaviour as the bug we talked about (as to expect). I've tested both a small and a large file using different methods (see DownloadTest.php). The downloaded file sometimes actually gets larger and on doing a diff it shows some different encoding (\HEX instead of a characters as in the original).

To download an image you have to understand how Puppeteer really handles this in pure JS:

```js
// See: https://github.com/puppeteer/puppeteer/issues/1937#issuecomment-366447465
const response = await page.goto('https://bringyourownideas.com/images/byoi-logo.jpg');
fs.writeFileSync('./byoi-logo.jpg', await response.buffer());
```

With PuPHPeteer, we can't transfer binary data across sockets (because, once again, the implementation sucks), but we can convert that to base64:

```php
// See: https://github.com/rialto-php/puphpeteer/issues/91#issuecomment-641116053
$response = $page->goto('https://bringyourownideas.com/images/byoi-logo.jpg');
$base64 = $response->buffer()->toString('base64');
file_put_contents('./byoi-logo.jpg', base64_decode($base64));
```

Before trying something with PuPHPeteer, you should really try with Puppeteer before. We can easily realize that we don't actually know how to do, happened to me many times too. 😅

And about PDF files, I think the issue is the same. 😉

>Directly 'goto' an URL doesn't work - I get a network error on this. While it works in the actual Chrome.

I'm not sure what you're trying to tell me here. Which part of your code are you talking about?

# About your commits

### MINOR: moving setup steps into basic TestCase to allow other classes to use it too

The commit is good and it's a good idea to move this code in the `TestCase` class. However, make sure your commits contain only what they describe, I can see things which shouldn't be there:

- `/** @test */`: I can perfectly you don't like the way it is written. I think we will add PHP_CodeSniffer in the projects to make sure everything is always written the same. However, in the meantime, if you have an automatic formatter, please disable it for the Rialto projects.
- Modification to `$incompleteText`: This should be done in another commit, it's not related to moving the setup steps.
- You have added 3 images, they shouldn't be in this commit too. And 2 of them are not used in your tests in the next commit. (maybe they will tho?)

Why I'm so strict on splitting our commits is because we should be able to revert one without reverting side things. Here, by reverting a commit about setup steps, we will also revert a new line and some images.

**Comment by spekulatius** [comment]
Hey @nesk 

you are right, I put in more my expectation of how it expected it to work than actually knowing how Puppeteer does work. Something to fix in my process. I'll start with finding and testing a Puppeteer example before trying to get anything working on the PHP side. Makes absolute sense - my mistake.

Yes, the PR wasn't intended to be merged (hence the three images etc.) - it's very WIP. I've got no problem with keeping it very granular. Makes sense and keeps it cleaner. I'll open a proper PR for the migration of the setup steps and we do it one by one from there.

Thanks for taking time debugging this :D

Cheers,
Peter

**Comment by spekulatius** [comment]
@nesk,

regarding `/** @test */`: I assume it's going to be mostly you and me working on it (for now at least). So maybe keeping it simple and concentrating on the core problems/tasks makes more sense. Should I just tidy it up in a separate PR and we keep an eye on it not getting messy for now? This way we keep an eye on the target.

**Comment by spekulatius** [comment]
Closing as completed in other PR

**Pull request closed without merging**
